### ISSUE TITLE
Numeric type (String to int)

### ISSUE THREAD

**Issue by seijihirao** [clubedaentrega/validate-fields#12]
Tipo numérico que receba uma stringa mas a transforme para número

**Comment by sitegui** [comment]
String numeric type that receives a string and parses that as an integer.

This is useful in some situations, where all values are strings. Like GET parameters, HTML tag attributes, etc

The number types we have by now are implemented in [types/numeric.js](https://github.com/clubedaentrega/validate-fields/blob/v3.2.0/types/numeric.js). Those are:

* Number
* 'number'
* 'int'
* 'uint'
* 'numberIn'

The string dual for those would be:

* 'numeric'
* 'numericInt'
* 'numericUint'
* 'numericIn'
